var GAME_LEVELS = [
  ["                                 |                                          ",
   " s                                                                          ",
   "                                                                            ",
   "                                                                            ",
   "                                                                            ",
   "                                                                            ",
   "                                                                            ",
   "                                                                            ",
   "                                           |                                ",
   "                           o                  o                             ",
   "                 oo     |xxxxxxx            xxxxxxx                         ",
   "                 oo       xxxxx              xxxxx                          ",
   "                 oo         x                  x                            ",
   "                 oo                    o                                    ",
   "               xxxxxx              xxxxxxxx                                 ",
   "           w   x    x               xxxxxx                                  ",
   "               xxxxxx                xxxx            o     o                ",
   " xx            x    x                                o     o    xxxxxxxxxxxx",
   "  x          xxxxxxxxxx                              o     o                ",
   "  x   @   xxxxxx    xxxxxx                           o     o         o  o  o",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxx",
   "                                                     x!!!!!x                ",
   "                                                     x!!!!!x                ",
   "                                                     x!!!!!x                ",
   "                                                     xxxxxxx                ",
   "                                                                           "],
  

  ["                                                                        ",
   "                                                                        ",
   "       s                                                           | |  ",
   "                                                                        ",   
   "                                                                        ",
   "                                             s                          ",
   "                                                                        ",
   "                                                                        ",
   "                                                                       o",
   "                              o       o                               xx",
   "                o  o         xxx     xxx                              xx",
   "              o      o       x x     x x                o       o     xx",
   "            o          o     x x     x x               xxx     xxx    xx",
   "            xxx      xxx  s  x x     x x      o        x x!!!!!x x    xx",
   "            x x      x x     x x     x x   xxxxxxxx    x x!!!!!x x    xx",
   "     @      x xx    xx x     x x!!!!!x x               x x!!!!!x x    xx",
   "    xxxs    x xx    xx x     x x!!!!!x x               x x!!!!!x x    xx",
   "    x x     x xx!!!!xx x     x x!!!!!x x               x x!!!!!x x    xx",
   "    x x     x xx!!!!xx x     x xx!!!xx x               x x!!!!!x x    xx",
   "    x x     x xxx!!xxx x     x xxxxxxx x               x x!!!!!x x    xx",
   "!   x x     x xxxxxxxx x     x xxxxxxx x               x x!!!!!x x    xx",
   "!!!!x x!!!!!x xxxxxxxx x  |  x xxxxxxx x |         |   x x!!!!!x x    xx",
   "!!!!x x!!!!!x xxxxxxxx xxxxxxx xxxxxxx xxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxx",
   "!!!!x x!!!!!x xxxxxxxx xxxxxxx xxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!x x!!!!!x x x x xx xx x x x x x x x x x x x x x x x x x x x x x xxx"],
  

  ["                                                                                      ",
   "s                                                                                     ",
   "                                                                                      ",
   "                                                                                      ",
   "                                                                                      ",
   "                                             xxxxxxxxx                                ",
   "                                             x                   xxxxxxxxxxxxxxxxxxxx ",
   "  x             x       o          o         x                        |             x ",
   "  x          |  x       xxxxxxxxxxxx         x                                      x ",
   "  x      | xxxxxx      xxxxxxxxxxxxxx        x            oooooo                    x ",
   "  x             x                            x |  o   |                             x ",
   "  x             x                            x                                      x ",
   "  x             x       o           o        x                                      x ",
   "  xxxxxx        x       xxxxxxxxxxxxx        xxxxxxxxxxxxxxx                        x ",
   "  x             x      xxxxxxxxxxxxxxx       x                      o         o     x ",
   "  x             x                            xxxxxxxxx                              x ",
   "  x          |  x       o            o                          xxxxxxxxxxxxxxxxxxxxx ",
   "  x        xxxxxx                                                 s                 x ",
   "  x             x    xxxxxxxxxxxxxxxxxxxx                                           x ",
   "  x             x                       x                      xxxxxxxxxxxxxxxxxxxxxx ",
   "  x  |          x                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "  xxxxxx        x                                                                     ",
   "  x             x                                                                     ",
   "  x             x  |                                                                  ",
   "  x       @     x                                                                     ",
   "  xxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                      ",
   "                                                                                      "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
